Code remastering to fix warning "Detected I/O inside the event loop" #2

diff --git a/script/setup b/script/setup
--- a/script/setup
+++ b/script/setup
@@ -1,10 +1,13 @@
 #!/bin/sh
+# Setups the repository.
 
-pip3 install pre-commit
-pip3 install -r requirements.txt -r requirements-dev.txt --user
+# Stop on errors
+set -e
+
+cd "$(dirname "$0")/.."
+script/bootstrap
+
 pre-commit install
-pre-commit autoupdate
-chmod a+x update_tracker.py
 
 CONFIG=/run/user/$(id -u)/gvfs/smb-share:server=hassio,share=config/
 if [ -d "$CONFIG" ] && [ ! -e dev-config ]; then
